//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicFinal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Entrance
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public byte[] password { get; set; }
        public Nullable<int> RoleTypeId { get; set; }
    
        public virtual TBL_RoleType TBL_RoleType { get; set; }
        public virtual TBL_User TBL_User { get; set; }
    }
}
